---
title: "Homework 4"
author: "Erika Luna"
date: "October 6, 2019"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(gapminder)
library(dplyr)
library(ggplot2)
library(knitr)
library(DT)
library(devtools)
```

#Exercise 1 - Univariate option 1:

```{r}
dat = gapminder %>%
  filter(country == "Mexico" | country == "Canada") %>%
  select(country, year, lifeExp) %>%
  pivot_wider(id_cols = year,
              names_from = country,
              names_prefix = "lifeExp_",
              values_from = lifeExp)

DT::datatable(dat)
```

```{r}
axis_lim = c(min(dat$lifeExp_Mexico, dat$lifeExp_Canada),
             max(dat$lifeExp_Mexico , dat$lifeExp_Canada))
dat %>%
  ggplot(aes(lifeExp_Mexico, lifeExp_Canada)) +
  geom_point(aes(colour = "red"), size = 3) +
  geom_abline(linetype = 2, alpha = 0.3) +
  geom_text(aes(label = year), size = 3, hjust = 1.3) +
  coord_fixed(xlim = axis_lim, ylim = axis_lim) +
  labs(title = "Life Expectancy (years) of Canada against Mexico",
       x = "Life Expectancy in Mexico",
       y = "Life Expectancy in Canada") +
  theme_bw() +
  theme(legend.position = "none")
```
```{r}
dat %>%
  pivot_longer(cols = c(lifeExp_Mexico, lifeExp_Canada),
               names_to = "country",
               names_prefix = "lifeExp_",
               values_to = "lifeExp") %>%
  DT::datatable()
```

#Exercise 2 / Multivariate Option 1: 
##Make a tibble with one row per year, and columns for life expectancy and GDP per capita (or two other numeric variables) for two or more countries.

```{r}
dat = gapminder %>%
  filter(country == "Mexico" | country == "Canada") %>%
  select(country, year, gdpPercap, lifeExp) %>%
  pivot_wider(id_cols = year,
              names_from = country,
              names_sep = "_",
              values_from = c("lifeExp", "gdpPercap"))
DT::datatable(dat)
```

##Re-lengthen the data.

```{r}
dat %>%
  pivot_longer(cols = -year,
               names_to = c(".value" ,"country"),
               names_sep = "_",
               values_to = c("lifeExp", "gdpPercap")) %>%
  DT::datatable()
```

#Exercise 3: Table Joins

```{r echo = FALSE, warning = FALSE, message = FALSE}
guest <- read_csv("https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/data/wedding/attend.csv")
email <- read_csv("https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/data/wedding/emails.csv")
```

##3.1


```{r}
email_modified <- 
  separate_rows(email, guest, sep = ", " ) %>% 
  rename(name = guest)

guest %>% 
  left_join(email_modified, by = "name")
  
#DT::datatable(email_modified)
```

##3.2

```{r}
non_guest <- email_modified %>%
  anti_join(guest, by = "name")


  knitr::kable(non_guest)
```

##3.3: Make a guestlist that includes everyone we have emails for (in addition to those on the original guestlist).

```{r}
bind_rows(email_modified, non_guest) %>% 
  DT::datatable()
```





