---
title: "Homework 3"
author: "Erika Luna"
date: "October 1, 2019"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(gapminder)
library(dplyr)
library(DT)
library(knitr)
```

#Instructions

In this assignment we will explore the gapminder dataset using the dplyr package.

## Task Option 2

Get the maximum and minimum of GDP per capita for all continents.

```{r tibble task2}
tmp <- gapminder %>% 
  group_by(continent) %>% 
  summarise(min_gdp = min(gdpPercap),
            max_gdp = max(gdpPercap))
  #knitr::kable()

tmp
```



```{r plot task2}
tmp %>% 
  ggplot(aes())+
  geom_point(aes(continent,max_gdp, colour = "red"))+
  geom_point(aes(continent,min_gdp, colour = "blue"))+
  labs(title="Minimum and maximum GDP of each continet",
               x="Continent",
               y="GDP per capita")+
  scale_color_discrete("",labels=c("Minimum GDP", "Maximum GDP"))+
  scale_y_log10(labels = scales::dollar_format())


```




## Task Option 3

Look at the spread of GDP per capita within the continents.

```{r tibble task3}
gapminder %>% 
  group_by(continent) %>% 
  summarize(max_gdpPercap = max(gdpPercap),
            min_gdpPercap = min(gdpPercap),
            range_gdpPercap = max(gdpPercap)-min(gdpPercap),
            sd_gdpPercap = sd(gdpPercap),
            mean_gdpPercap = mean(gdpPercap),
            median_gdpPercap = median(gdpPercap)) %>% 
  knitr::kable()
```


```{r plot tisk3}
gapminder %>% 
  ggplot(aes(continent, gdpPercap)) +
  geom_boxplot() +
  scale_y_log10(labels = scales::dollar_format()) +
  labs(title = "Spread of GDP per capita for all continents", 
       x = "Continent", 
       y = "GDP per capita")
```



## Task Option 5

How is life expectancy changing over time on different continents?


```{r tibble task5}
gapminder %>% 
  group_by(continent, year) %>% 
  summarise(mean_life = mean(lifeExp)) %>% 
  DT::datatable()
```


```{r plot task5}
gapminder %>% 
  ggplot(aes(year, lifeExp, group = country, colour = continent)) +
  geom_jitter(size = 1, alpha = 0.5)+
  geom_line()+
  facet_wrap(~ continent, nrow = 3)  +
  labs(title = "Change of life expectancy over time", 
       x = "Year", 
       y = "Country life expectancy (mean)")
```
